services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot_certs:/etc/letsencrypt
      - ./certbot_www:/var/www/certbot
    depends_on:
      - open-webui
      - searxng
    networks:
      - ai-frontend # Apenas na zona pública/fronteira

  searxng:
    image: searxng/searxng
    container_name: searxng
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - ./searxng:/etc/searxng
      - searxng-cache:/var/cache/searxng
    environment:
      - SEARXNG_SECRET=${SEARXNG_SECRET}
      - SEARXNG_LIMITER=${SEARXNG_LIMITER}
      - SEARXNG_VALKEY_URL=valkey://valkey:6379/0
    depends_on:
      - valkey
    networks:
      - ai-frontend # Para receber tráfego do Nginx
      - ai-backend  # Para conversar com o Valkey

  valkey:
    image: valkey/valkey:alpine
    container_name: valkey
    restart: unless-stopped
    expose:
      - "6379"
    networks:
      - ai-backend # Isolado no backend

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    expose:
      - "11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - ai-backend # Isolado no backend

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    expose:
      - "8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - SCARF_NO_ANALYTICS=true
      - DO_NOT_TRACK=true
      - ANONYMIZED_TELEMETRY=false
    depends_on:
      - searxng
      - ollama
    networks:
      - ai-frontend # Para receber tráfego do Nginx
      - ai-backend  # Para conversar com o Ollama e SearXNG

volumes:
  searxng-cache:
  open-webui:
  ollama-data:

# Definição e criação das redes isoladas
networks:
  ai-frontend:
    driver: bridge
  ai-backend:
    driver: bridge
    internal: true # Bloqueia qualquer tráfego de saída/entrada externo para esta rede
